name: Gatling Performance Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          architecture: x64
      
      - name: Build with Maven
        run: mvn clean install
      
      - name: Run Gatling Tests
        run: mvn gatling:test "-Dgatling.simulationClass=gatling.BasicSimulation"
      
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: gatling-results
          path: target/gatling